version: '3'

services:
###> doctrine/doctrine-bundle ###
  apps:
    container_name: dtc-symfony
    build:
      context: docker/app
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/dtc-formation:rw+
      - ./docker/apache_conf:/etc/apache2/sites-enabled

  mailer:
    container_name: mailer-dtc
    image: schickling/mailcatcher
    ports:
      - "8082:1025"
      - "8083:1080"

  database:
    image: mysql:latest
    container_name: mysql-dtc
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: julkwel
      MYSQL_DATABASE: dtc-symfony
      MYSQL_USER: whole
      MYSQL_PASSWORD: wh0leL1f3
    volumes:
      - "$PWD/data:/var/lib/mysql:rw"
